project:
  type: website
  output-dir: _site

website:
  title: "Fedor V. Gerasimov"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
  page-footer:
    left: "Â© 2025 Fedor Gerasimov"
    right: "Built with Quarto"

format:
  html:
    theme: litera
    toc: true
    css: styles.css
